### ISSUE TITLE
打包配置dist文件名 替换成release，打包后仍然生成dist文件夹

### ISSUE THREAD

**Issue by syy1992** [seizeDev/vue-more-pages#11]
我把所有配置涉及到dist 的文件夹 替换成release了，但是运行完打包命令过后仍然生成dist文件夹。

**Comment by seizeDev** [comment]
文件加是dist没问题，我说的 dist是打包部署生产环境的公共url前缀，看redeme里面的注意

**Comment by do996icu** [comment]
我看了这个会将模块下面的chunk文件还是提出来了；但是对于多业务线模块的话还是有缺陷，比如业务A和业务B，打包之后如果业务B有修改，还是的把AB两个业务模块全部编译打包一次。

**Comment by seizeDev** [comment]
这个需要写指定编译文件
