### ISSUE TITLE
多文件打包后，引用js的标签为link

### ISSUE THREAD

**Issue by wuzf007** [seizeDev/vue-more-pages#12]
多文件应用打包后，html页面引用的chunk-common.68384993.css为当前文件夹下的css和js，实际上他们都被打包到public下的css文件夹里面了。
同时打包的时候报：{ [Error: ENOENT: no such file or directory, open 'D:\HBuilderProject\apptest\mainstage\mainstage\dist\chunk-common\js\chunk-common.c6ac2d9b.js']

**Comment by seizeDev** [comment]
close
