### ISSUE TITLE
低版本兼容

### ISSUE THREAD

**Issue by sheak** [seizeDev/vue-more-pages#13]
请问针对安卓的低版本兼容该如何处理呢？
一般都要通过安装’babel-polyfill‘来实现， 但是现在entry已经改了
我尝试引入相关依赖包，然后修改getPages.js 关于entry 部分， 打包的时候报错

entry: ['babel-polyfill', `src/pages/${fileName}/${fileName}.js`]

**Comment by seizeDev** [comment]
直接html引入cdn  babel-polyfill
