### ISSUE TITLE
css 引入 背景图片 路径不对

### ISSUE THREAD

**Issue by qinouz** [seizeDev/vue-more-pages#18]
![image](https://user-images.githubusercontent.com/19344660/82426769-d799d900-9aba-11ea-8dcc-394a4dca1f02.png)
![image](https://user-images.githubusercontent.com/19344660/82426786-de285080-9aba-11ea-8805-65e86415aec3.png)

**Comment by seizeDev** [comment]
已修复，之前是因为CSS文件位置移了，导致IMAGE文件路径引用错误
