### ISSUE TITLE
有一些问题

### ISSUE THREAD

**Issue by zSh4dow** [seizeDev/vue-more-pages#4]
打包后本地html文件的静态文件路径不对啊，package.json里的vue和vue-cli也该更新了

**Comment by Yan1513149392** [comment]
配置了pages，怎么能配置publicPath呐？
但是问题又来了没法配置publicPath，页面出现空白页，这是个问题

**Comment by seizeDev** [comment]
最新vue.config.js publicPath已经配好了，默认是dist,可以修改

**Comment by seizeDev** [comment]
html文件的静态文件路径已经修复
